substitutions:
  name: "soil-monitor-00007"
  friendly_name: Bedroom Left Plant
  raw_full_value: "1.96"
  raw_empty_value: "3.15"
  tuned_full_value: "1.96"
  tuned_empty_value: "3.15"

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: diagnostic

text_sensor:
  - platform: version
    hide_timestamp: true
    name: "ESPHome Version"
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:wifi
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic

sensor:
  - platform: adc
    id: raw_voltage
    pin: GPIO34
    name: "Raw Voltage"
    icon: "mdi:flash"
    update_interval: 30s
    attenuation: auto
  - platform: copy
    id: averaged_voltage
    source_id: raw_voltage
    name: "Averaged Voltage"
    unit_of_measurement: "V"
    icon: "mdi:flash"
    filters:
      - median:
          window_size: 30
          send_every: 30
          send_first_at: 1
  - platform: copy
    id: raw_soil_moisture_uncapped
    source_id: raw_voltage
    name: "Raw Soil Moisture Uncapped"
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    accuracy_decimals: 2
    filters:
    - calibrate_linear:
      - ${raw_full_value} -> 100.00
      - ${raw_empty_value} -> 0.00
  - platform: copy
    id: raw_soil_moisture
    source_id: raw_soil_moisture_uncapped
    name: "Raw Soil Moisture"
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    accuracy_decimals: 2
    filters:
    - lambda: |
        if (x < 0) return 0; 
        else if (x > 100) return 100;
        else return (x);
  - platform: copy
    id: tuned_soil_moisture_uncapped
    source_id: averaged_voltage
    name: "Tuned Soil Moisture Uncapped"
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    accuracy_decimals: 2
    filters:
    - median:
        window_size: 8
        send_every: 2
        send_first_at: 1
    - calibrate_linear:
      - ${tuned_full_value} -> 100.00
      - ${tuned_empty_value} -> 0.00
  - platform: copy
    id: tuned_soil_moisture
    source_id: tuned_soil_moisture_uncapped
    name: "Tuned Soil Moisture"
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    accuracy_decimals: 2
    filters:
    - lambda: |
        if (x < 0) return 0; 
        else if (x > 100) return 100;
        else return (x);