globals:
  - id: initial_empty
    type: float
    restore_value: yes
    initial_value: '${initial_empty_value}'
  - id: initial_full
    type: float
    restore_value: yes
    initial_value: '${initial_full_value}'
    
sensor:
  - platform: adc
    id: raw_voltage
    pin: GPIO34
    name: Raw Voltage
    icon: "mdi:flash"
    update_interval: 5s
    attenuation: auto
  - platform: copy
    source_id: raw_voltage
    name: Adjusted Soil Moisture
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    filters:
    - median:
        window_size: 8
        send_every: 2
        send_first_at: 1
    - calibrate_linear:
      - $initial_full_value -> 100.00
      - $initial_empty_value -> 0.00
    - lambda: |
        if (x < 0) return 0; 
        else if (x > 100) return 100;
        else return (x);
    accuracy_decimals: 2
  - platform: template
    name: "Template Sensor"
    lambda: return id(raw_voltage).state
    update_interval: 5s